# Makefile for gRPC Operation Service with PostgreSQL

# Service Name
SERVICE=operation

# Base service Makefile
include ../Makefile.service


script-start:
	@go run ./scripts/start_operation/main.go

script-check:
	@go run ./scripts/check_operation/main.go